### ISSUE TITLE
Repository clean up and commit renaming

### ISSUE THREAD

**Issue by lululujojo123** [lululujojo123/BattleCreatures#11]
I did some commits and repository clean up. Therefore I made some rebases and after that the offline repositories aren't synchronized any more. Please delete your local repository and make a fresh clone.

1. Back up all pending changes without commiting (copying into another folder)
2. Immediatly delete the repository without fetching, commiting or merging any branches or changes
3. Clone the repository again with GitHub Desktop
4. Switch to the correct branch !!!! We won't work directly on the main branch !!!! 
4. Copy the files back to your active git repo
5. Finish the changes if required or just commit and push the changes to origin !!!! Please don't push diectly to main branch except from minor exceptions after noticing the other developers !!!!

From now on we will only work on feature branches and use pull requests for merging back to main branch.

Please answer to this topic when finished with the recloning of the repository so we can close that issue as soon as possible.

**Comment by lululujojo123** [comment]
I finished the reclone and the local clean up of my git repository folder.

@laraltb: Please notice me here after finishing the clean up. I will close the issue after that.

**Comment by lululujojo123** [comment]
@laraltb Did you already reclone the repository? So I could close this issue.

**Comment by lululujojo123** [comment]
@laraltb Did you finish the fresh clone already or do you need any help?

**Comment by laraltb** [comment]
Sorry for the late answer! Yes I recloned the repository.

**Comment by lululujojo123** [comment]
Okay. Thank you. I will close this issue.
