### ISSUE TITLE
Creating UI-Tests and maybe unit tests for the application

### ISSUE THREAD

**Issue by lululujojo123** [lululujojo123/BattleCreatures#15]
Creating some minor UI-Tests according to the points metioned by the profs.

- [x] First start of app with tutorial
- [x] Second start tutorial won't appear
- [x] Maybe the start of profile activity

If required some minor unit tests for the exp calculation of player.

**Comment by laraltb** [comment]
Do I need to make a new branch to work on the UI Tests or can I do it in the main branch?

**Comment by lululujojo123** [comment]
@laraltb Please in New Branch. We won't work direktly in the main Branch. I think it shouldn't be possible to push into the main branch as well. Ohh. And please delete your local branches for all the branches we already deleted after Merging.

**Comment by laraltb** [comment]
Ok I made a new branch.
