### ISSUE TITLE
Cards design

### ISSUE THREAD

**Issue by lululujojo123** [lululujojo123/BattleCreatures#6]
The cards need to be designed. We need 2 front view versions. One in German and one in English. The back of the card needs to be designed only once.

[Naming convention]
<charactername>_<front|back>(_de)

@laraltb will do that design work.

**Comment by lululujojo123** [comment]
@laraltb How are the cards at the moment? Did you finished something? Maybe you can upload a png to a comment here in this issue and we can discuss on it a little bit. 😊

**Comment by lululujojo123** [comment]
@laraltb Any updates on this issue? Or some questions or something to talk about?

**Comment by laraltb** [comment]
![swordsman_front_de](https://user-images.githubusercontent.com/58517339/103541162-45a0de00-4e9b-11eb-8504-dbf37c088e14.png)

This is how far I am at the moment. I'll finish the other cards later today. If you have any suggestions or improvement ideas please let me know :)

**Comment by lululujojo123** [comment]
They are really beautiful. I am really excited. I am sure they will look great after printing them. 👌 Could you store them in the CardsDataAndImage Branch after finishing? Once in png format and once in svg format if possible.

**Comment by lululujojo123** [comment]
Unfortunately the card printing service we considered to use cannot rint our cards. Therefore I think, that just simply printing on thick paper should be enough. Not that nice but better then nothing.

**Comment by laraltb** [comment]
I uploaded all of the front sides now. I still have to do the back side. 
And I think printing on thick paper should be okay too.

**Comment by lululujojo123** [comment]
Nice. So I can use it in the Cards Deck Management Activity later. I really like your card design. 👌 Maybe we can meet every Thursday from now until the final deadline. Unfortunately today and tomorrow I won't be able to do a lot for our project.

**Comment by laraltb** [comment]
I uploaded the back sides. This issue is done now right?

**Comment by lululujojo123** [comment]
I'll close that issue after finishing the interlinking with the json document. Unfortunately I did a wrong presumption on the workload of the home activity. I am still not ready. I'll do that after finishing the home activity.

**Comment by lululujojo123** [comment]
I finally added the picture links into the json document and merged the branch into the main branch. As we may not need that branch any more, I deleted the cards data branch. I'll close this issue.
