### ISSUE TITLE
Implementing the ProfileActivity

### ISSUE THREAD

**Issue by lululujojo123** [lululujojo123/BattleCreatures#8]
Creating the ProfileActivity with all the required information of your own profile.

- [x] Player name and change option
- [x] Current level and next level
- [x] Current exp and exp for the next level

!!! List of games will be added later in a new branch because of pull request problematics !!!

**Comment by lululujojo123** [comment]
@laraltb How is it going? Any problems or something you want to discuss? Maybe a first screenshot or something like that?

**Comment by lululujojo123** [comment]
Hey @laraltb. Could you please change the background color to yellow_500? That would fit better to my transition idea. Thank you very much.

**Comment by laraltb** [comment]
Yes I changed the background color, I still have to replace the buttons with icons and make the overall layout look more appealing.

**Comment by lululujojo123** [comment]
@laraltb How is it going. Did you finish the Profile Activity already? I finished and closed the HomeActivity issue. I think that activity is now good enough.

**Comment by laraltb** [comment]
I just opened a pull request because the Profile Activity is so far finished. However I'm not 100% satisfied with the Animations but this is the best I could do. If you have any ideas to improve it please tell me. Otherwise the Profile Activity is done now.
