### ISSUE TITLE
CleanUp and finalizing the HomeActivity

### ISSUE THREAD

**Issue by lululujojo123** [lululujojo123/BattleCreatures#9]
The HomeActivity and the preparation class has to be cleanuped and finalized.

- [x] Cleanup
- [x] Finalizing the HomeActivity with animations
- [x] Finalizing the preparation tasks

!!! The connection to other activities will be done in other branch !!!

**Comment by lululujojo123** [comment]
Unfortunately I got problems on doing a proper and clean information dialog for the user, when the API sync has failed. So my cleanup and finalizing work has been delayed. I'll work on it again propably tomorrow or on Monday. Because of Economics course.

![Screenshot_20210102_142605_org.battlecreatures.jpg](https://user-images.githubusercontent.com/76261866/103458251-84515f80-4d06-11eb-900a-9bbe30cc75c8.jpg)

@laraltb What do you think about it? Is it a proper Error message or should I change it?

**Comment by lululujojo123** [comment]
I tried a few performance tweaks I read online. But I think the splash screen will simply take a few seconds. Because the sync process simply takes a while.

Unfortunately I am a little sick again so I didn't program a lot. But I will do the cleanup of the project and implement the on click listener removing in the on destroy method as soon as possible.

After that I will finish the design of the HomeActivity. And start with the Cards Management Activity.

**Comment by lululujojo123** [comment]
I did some project cleanup and did researches on garbage collection and activity life cycle. I think all the fields of a activity should be garbage collected after calling the finish() method as the activity is queued for destruction. But I added a manually garbage cycle to the queue in the onDestroy method.

I do also finalized the application preparation in first place.

The home activity finalization I scheduled for the Wednesday or something like that as I have no time tomorrow.

**Comment by lululujojo123** [comment]
Unfortunately it look a little longer to create proper animations for the profile progress bar. So I'll do the rest of the home screen animations and an interactions tomorrow. Hopefully I can finalize and merge the HomeActivity tomorrow. I'll show my progress on Thursday.

**Comment by lululujojo123** [comment]
Sorry but I tried to create the background assets from within android studio and it seemed to really don't work. Therefore I have to create the assets again and reanimated the transitions to the next activity. I'll try to finish it tomorrow.

**Comment by lululujojo123** [comment]
I think I figured out the problem with my idea. The main menu is now looking a little different but I think still pretty similar and nice. I'll finish the whole home screen stuff until tomorrow hopefully and will merge the cards data as well. Thank you for the patience. I'll do a little break now.

**Comment by lululujojo123** [comment]
@laraltb We need to check the animation or ConstraintLayouts again because there seems to be a graphical glitch on the brown background shape while animating. But it seems like that issue only appeared on my hardware phone. Please test that on your virtual phone as well and maybe on your hardware phone. If there isn't any glitch I would say we keep that issue open and solve the bug later or mabe just ignore it.

**Comment by laraltb** [comment]
I tested it on the emulator and I didn't see any glitches. I think we can take care of this at the end if we still have time or just ignore it.

**Comment by lululujojo123** [comment]
Currently found and fixed the bug causing the unclickable issue after resuming the activity.

Also fixed the animation glitch when resuming after closing the app while an animation transition was in progress.

The graphical glitch is also fixed.

I will merge that branch and create a new branch for the CardDeck functionality. I'll close that issue.
